

CREATE TABLE `transcripcions` (
  `id_transcripcio` int(11) NOT NULL AUTO_INCREMENT,
  `id_document` int(11) NOT NULL,
  `id_marit` int(11) NOT NULL,
  `id_pare_marit` int(11) NOT NULL,
  `id_mare_marit` int(11) NOT NULL,
  `id_esposa` int(11) NOT NULL,
  `id_pare_esposa` int(11) NOT NULL,
  `id_mare_esposa` int(11) NOT NULL,
  `dia` int(11) NOT NULL,
  `mes` int(11) NOT NULL,
  `ano` int(11) NOT NULL,
  `parroquia` text,
  `impost` text,
  `numero` int(11) NOT NULL,
  `puntets` enum('0','1') NOT NULL DEFAULT '0',
  `observacions` text,
  `data_creacio` datetime NOT NULL,
  `creada_per` int(11) NOT NULL,
  `liquidacio` enum('0','1') NOT NULL DEFAULT '0',
  `text_liquidacio` text,
  `data_modificacio` datetime DEFAULT NULL,
  `modificada_per` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_transcripcio`),
  KEY `fk_trasc_pers_1` (`id_marit`),
  KEY `fk_trasc_pers_2` (`id_pare_marit`),
  KEY `fk_trasc_pers_3` (`id_mare_marit`),
  KEY `fk_trasc_pers_4` (`id_esposa`),
  KEY `fk_trasc_pers_5` (`id_pare_esposa`),
  KEY `fk_trasc_pers_6` (`id_mare_esposa`),
  KEY `fk_trasc_usua` (`creada_per`),
  CONSTRAINT `fk_trasc_pers_1` FOREIGN KEY (`id_marit`) REFERENCES `persones` (`id_persona`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_trasc_pers_2` FOREIGN KEY (`id_pare_marit`) REFERENCES `persones` (`id_persona`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_trasc_pers_3` FOREIGN KEY (`id_mare_marit`) REFERENCES `persones` (`id_persona`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_trasc_pers_4` FOREIGN KEY (`id_esposa`) REFERENCES `persones` (`id_persona`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_trasc_pers_5` FOREIGN KEY (`id_pare_esposa`) REFERENCES `persones` (`id_persona`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_trasc_pers_6` FOREIGN KEY (`id_mare_esposa`) REFERENCES `persones` (`id_persona`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_trasc_usua` FOREIGN KEY (`creada_per`) REFERENCES `usuaris` (`id_usuari`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=600531 DEFAULT CHARSET=utf8;


CREATE TABLE `persones` (
  `id_persona` int(11) NOT NULL AUTO_INCREMENT,
  `id_transcripcio` int(11) DEFAULT NULL,
  `tractament` text,
  `nom` text,
  `cognom1` text,
  `cognom2` text,
  `estat_civil` varchar(45) DEFAULT NULL,
  `ocupacio` text,
  `origen` text,
  `residencia` text,
  `vidu_de` text,
  `difunt` enum('0','1') DEFAULT '0',
  `ocupacio_difunt` text,
  `residencia_difunt` text,
  `cognom1_norm` varchar(45) DEFAULT NULL,
  `tipus` text,
  `cognom2_norm` varchar(45) DEFAULT NULL,
  `ocupacio_norm` varchar(200) DEFAULT NULL,
  `residenica_norm` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id_persona`),
  KEY `fk_pers_transc` (`id_transcripcio`),
  CONSTRAINT `fk_pers_transc` FOREIGN KEY (`id_transcripcio`) REFERENCES `transcripcions` (`id_transcripcio`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3502798 DEFAULT CHARSET=utf8;
